re-add missing BUILD file
ResolveError: Directory 'st2api/st2api/controllers/exp' does not contain any BUILD files.
ResolveError: Directory 'st2auth/st2auth/controllers' does not contain any BUILD files.
ResolveError: Directory 'st2stream/st2stream/controllers' does not contain any BUILD files.